
logging:
  level:
    root: error
    org.ktorm: debug

spring:
  datasource:
    url: jdbc:mysql://192.168.39.143:3306/ifaas_community_gateway
    username: root
    password: introcks1234
    driver-class-name: com.mysql.jdbc.Driver #mysql-connector-java 8不需要